# Generated by Django 3.1.7 on 2022-08-15 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
    ]
