# Generated by Django 3.1.7 on 2022-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220815_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.CharField(default='etst', max_length=255),
            preserve_default=False,
        ),
    ]
