# Generated by Django 3.1.7 on 2022-08-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='category',
        ),
    ]
