# Generated by Django 4.1 on 2022-08-21 09:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(default='Default Body Text'),
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('transfers', ckeditor.fields.RichTextField()),
                ('stats', ckeditor.fields.RichTextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=100)),
                ('referee', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=10)),
                ('burnley_scorers', models.CharField(max_length=255)),
                ('opponent_scorers', models.CharField(max_length=255)),
                ('burnley_team', ckeditor.fields.RichTextField()),
                ('opponent_team', ckeditor.fields.RichTextField()),
                ('stats', ckeditor.fields.RichTextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
