# Generated by Django 4.1 on 2022-08-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_body_playerprofile_matchreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchreport',
            name='article',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='match_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.matchreport'),
        ),
        migrations.AddField(
            model_name='article',
            name='player_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.playerprofile'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
