# Generated by Django 4.1 on 2022-08-21 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_matchreport_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
