# Generated by Django 4.1 on 2022-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_playerprofile_transfers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchreport',
            old_name='referee',
            new_name='officials',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='burnley_scorers',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='opponent_scorers',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='score',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='stats',
        ),
        migrations.AddField(
            model_name='matchreport',
            name='corners_burnley',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='corners_opponent',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='fouls_burnley',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='fouls_opponent',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='goals',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='possession_burnley',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='possession_opponent',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='shots_burnley',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='shots_on_target_burnley',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='shots_on_target_opponent',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='shots_opponent',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
