# Generated by Django 4.1 on 2022-08-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_rename_referee_matchreport_officials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchreport',
            name='goals',
        ),
        migrations.AddField(
            model_name='matchreport',
            name='burnley_goals',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='burnley_scorers',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='opponent_goals',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreport',
            name='opponent_scorers',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
