# Generated by Django 4.1 on 2022-09-01 14:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_matchreport_goals_matchreport_burnley_goals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='stats',
            new_name='player_stats',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='current_job',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='international_caps_goals',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='manager_stats',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
