# Generated by Django 4.1 on 2022-09-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_rename_stats_playerprofile_player_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='banner',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
