# Generated by Django 4.1 on 2022-09-06 10:15

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_article_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(default='Enter the article body here...'),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='burnley_team',
            field=ckeditor.fields.RichTextField(default='<p><small>GK</small>:<br/><small>LB</small>:<br/><small>CB</small>:<br/><small>CB</small>:<br/><small>RB</small>:<br/><small>CDM</small>:<br/><small>CM</small>:<br/><small>CM</small>:<br/><small>LW</small>:<br/><small>RW</small>:<br/><small>ST</small>:</p>'),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='opponent_team',
            field=ckeditor.fields.RichTextField(default='<p><small>GK</small>:<br/><small>LB</small>:<br/><small>CB</small>:<br/><small>CB</small>:<br/><small>RB</small>:<br/><small>CDM</small>:<br/><small>CM</small>:<br/><small>CM</small>:<br/><small>LW</small>:<br/><small>RW</small>:<br/><small>ST</small>:</p>'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='current_job',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='dob',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='manager_stats',
            field=ckeditor.fields.RichTextField(blank=True, default='<table class="table table-bordered"><thead><tr><th>Team</th><th>Start</th><th>End</th><th>Played</th><th>Win</th><th>Draw</th><th>Lose</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>', null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='player_stats',
            field=ckeditor.fields.RichTextField(default='<table class="table table-bordered"><thead><tr><th>Team</th><th>Season</th><th>League</th><th>Apps</th><th>Goals</th><th>Assists</th><th>Clean Sheets</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>'),
        ),
    ]
