# Generated by Django 4.1 on 2022-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_article_short_snippet_alter_article_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='article',
            name='short_snippet',
        ),
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
